name:                graham-scan
version:             0.1.0.0
github:              "githubuser/graham-scan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/graham-scan#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.3 && < 2
- tasty >= 1.1 && < 2
- tasty-hunit >= 0.10 && < 1
- tasty-smallcheck >= 0.8 && < 1
- tasty-quickcheck >= 0.10 && < 1

library:
  source-dirs: src

executables:
  graham-scan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graham-scan

tests:
  graham-scan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graham-scan
